### ISSUE TITLE
Tracking v3

### ISSUE THREAD

**Issue by MierenManz** [SkyStar-modules/denoFFMPEG#9]
this issue is for discussing and tracking changes that will happen in v3

- [ ] Change `save()` & `saveWithProgress()` into
`output` for setting output and `render` to start the render
- [ ] Remove `outputFPS()` in favor of an output option in `output()`
- [ ] Rewrite internals to simplify the way of outputting (this should help with piping support)
- [ ] Add piping support
